// lib/products.js — Product data for all Krave Microgreens

export const products = [
  {
    slug: "broccoli",
    name: "Broccoli",
    tagline: "The King of Microgreens",
    emoji: "🥦",
    color: "#2d6a4f",
    bgGradient: "from-emerald-50 to-green-100",
    flavor: "Mild, slightly earthy with a hint of broccoli",
    texture: "Tender, crisp stems with delicate leaves",
    category: "Brassica",
    growDays: "8-12 days",
    featured: true,
    image: "/images/broccoli.jpg",
    excerpt: "Broccoli microgreens are nutritional powerhouses packed with sulforaphane — a potent compound linked to cancer prevention and cellular detox.",
    benefits: [
      "40× more sulforaphane than mature broccoli",
      "Powerful antioxidant and anti-inflammatory properties",
      "Supports liver detoxification",
      "Rich in Vitamin C, K, and folate",
      "Boosts immune function",
    ],
    nutrition: {
      "Vitamin C": "40× more than mature",
      "Sulforaphane": "Very high",
      "Vitamin K": "Excellent source",
      "Folate": "High",
      "Beta Carotene": "Rich",
    },
    usage: [
      "Add to salads as a nutrient-dense topping",
      "Blend into green smoothies",
      "Use as a sandwich or wrap filling",
      "Top soups and stews just before serving",
      "Garnish grain bowls and Buddha bowls",
    ],
    recipes: [
      {
        name: "Green Detox Smoothie",
        description: "Blend broccoli microgreens with banana, spinach, ginger, and coconut water for a powerful morning detox.",
      },
      {
        name: "Broccoli Micro Salad",
        description: "Toss with lemon vinaigrette, toasted sesame seeds, and sliced avocado.",
      },
    ],
    storage: "Store in the refrigerator in a sealed container. Consume within 5–7 days of delivery for peak freshness.",
  },
  {
    slug: "kale",
    name: "Kale",
    tagline: "Nature's Multivitamin",
    emoji: "🌿",
    color: "#1a3d2b",
    bgGradient: "from-green-50 to-emerald-100",
    flavor: "Mild, slightly nutty with earthy undertones",
    texture: "Tender and succulent",
    category: "Brassica",
    growDays: "10-12 days",
    featured: true,
    image: "/images/kale.jpg",
    excerpt: "Kale microgreens deliver an exceptional concentration of vitamins A, C, and K along with powerful phytonutrients for optimal health.",
    benefits: [
      "Exceptional source of Vitamins A, C, and K",
      "Rich in calcium for bone strength",
      "Powerful antioxidant protection",
      "Supports heart health",
      "Anti-inflammatory properties",
    ],
    nutrition: {
      "Vitamin K": "4× more than mature kale",
      "Vitamin C": "Excellent source",
      "Calcium": "High",
      "Iron": "Good source",
      "Lutein": "Rich",
    },
    usage: [
      "Perfect for green smoothies and juices",
      "Add to salads for extra nutrition",
      "Use in wraps and sandwiches",
      "Top avocado toast with kale microgreens",
      "Mix into pasta or grain dishes",
    ],
    recipes: [
      {
        name: "Kale Micro Power Bowl",
        description: "Layer kale microgreens over quinoa with roasted sweet potato, chickpeas, tahini drizzle, and lemon.",
      },
    ],
    storage: "Keep refrigerated in an airtight container. Best consumed within 5–7 days.",
  },
  {
    slug: "beetroot",
    name: "Beetroot",
    tagline: "Nature's Performance Booster",
    emoji: "🫑",
    color: "#7b2d8b",
    bgGradient: "from-purple-50 to-pink-100",
    flavor: "Earthy, slightly sweet with mild beet notes",
    texture: "Crisp stems with tender magenta-veined leaves",
    category: "Root Vegetable",
    growDays: "10-14 days",
    featured: true,
    image: "/images/beetroot.jpg",
    excerpt: "Beetroot microgreens are vivid in color and flavor, loaded with nitrates that naturally boost athletic performance and circulation.",
    benefits: [
      "High in dietary nitrates for cardiovascular health",
      "Natural performance and endurance booster",
      "Rich in Vitamin C and folate",
      "Supports healthy blood pressure",
      "Anti-inflammatory and antioxidant rich",
    ],
    nutrition: {
      "Nitrates": "Very high",
      "Vitamin C": "Good source",
      "Folate": "Excellent",
      "Betaine": "Rich",
      "Iron": "Present",
    },
    usage: [
      "Add visual drama to salads and plates",
      "Blend into beet smoothies for earthy sweetness",
      "Garnish soups (especially borscht)",
      "Use in grain bowls for color and nutrition",
      "Top hummus or dips",
    ],
    recipes: [
      {
        name: "Beet Glow Smoothie",
        description: "Blend beetroot microgreens with frozen berries, banana, ginger, and coconut water.",
      },
    ],
    storage: "Refrigerate in airtight container. Use within 5–7 days.",
  },
  {
    slug: "sunflower",
    name: "Sunflower",
    tagline: "Crunchy Protein Powerhouse",
    emoji: "🌻",
    color: "#b58c2d",
    bgGradient: "from-yellow-50 to-amber-100",
    flavor: "Nutty, rich, slightly sweet — like sunflower seeds",
    texture: "Thick, crunchy stems with bold leaves",
    category: "Seed",
    growDays: "10-14 days",
    featured: false,
    image: "/images/sunflower.jpg",
    excerpt: "Sunflower microgreens are the most satisfying to eat — bold, nutty flavor with a satisfying crunch and high plant-based protein content.",
    benefits: [
      "High in plant-based protein",
      "Rich in Vitamin E and essential amino acids",
      "Excellent source of healthy fats",
      "Supports skin and hair health",
      "Zinc, magnesium, and B vitamins",
    ],
    nutrition: {
      "Protein": "High — complete amino acids",
      "Vitamin E": "Excellent source",
      "Zinc": "Good source",
      "Healthy Fats": "Rich",
      "B Vitamins": "High",
    },
    usage: [
      "Add crunch to salads as a topping",
      "Use in sandwiches in place of lettuce",
      "Perfect for wraps and tacos",
      "Blend into smoothies for protein boost",
      "Great as a standalone snack",
    ],
    recipes: [
      {
        name: "Sunflower Crunch Salad",
        description: "Toss sunflower microgreens with shredded cabbage, mango, lime dressing, and toasted pumpkin seeds.",
      },
    ],
    storage: "Keep refrigerated. Best within 5–7 days of harvest.",
  },
  {
    slug: "wheatgrass",
    name: "Wheatgrass",
    tagline: "The Legendary Superfood",
    emoji: "🌾",
    color: "#4a7c59",
    bgGradient: "from-lime-50 to-green-100",
    flavor: "Intensely grassy, earthy, slightly sweet",
    texture: "Slender grass blades",
    category: "Cereal Grass",
    growDays: "7-10 days",
    featured: false,
    image: "/images/wheatgrass.jpg",
    excerpt: "Wheatgrass is the classic superfood shot — dense with chlorophyll, enzymes, and a complete spectrum of vitamins and minerals.",
    benefits: [
      "Rich in chlorophyll for blood cleansing",
      "Contains all essential amino acids",
      "Powerful alkalizing effect on the body",
      "Supports detoxification and liver health",
      "High in vitamins A, C, E, and K",
    ],
    nutrition: {
      "Chlorophyll": "Very high",
      "Vitamin A": "Excellent",
      "Vitamin C": "Good",
      "Iron": "Present",
      "Amino Acids": "Complete spectrum",
    },
    usage: [
      "Best consumed as a fresh-pressed shot",
      "Blend with citrus to mask the grassy flavor",
      "Add to green juices",
      "Mix into smoothies in small amounts",
    ],
    recipes: [
      {
        name: "Morning Detox Shot",
        description: "Press fresh wheatgrass with lemon juice and a pinch of ginger. Drink on an empty stomach.",
      },
    ],
    storage: "Store upright in refrigerator with roots. Best used within 7 days.",
  },
  {
    slug: "cilantro",
    name: "Cilantro",
    tagline: "Aromatic Herb Micro",
    emoji: "🌱",
    color: "#5a8c3d",
    bgGradient: "from-green-50 to-lime-100",
    flavor: "Bold, bright cilantro flavor — herbaceous and citrusy",
    texture: "Delicate, lacy leaves on slender stems",
    category: "Herb",
    growDays: "14-21 days",
    featured: false,
    image: "/images/cilantro.jpg",
    excerpt: "Cilantro microgreens concentrate the beloved herb's signature flavor into tiny, intensely aromatic leaves perfect for Indian and Mexican cuisine.",
    benefits: [
      "Natural heavy metal chelation properties",
      "Rich in Vitamins A, C, and K",
      "Supports digestive health",
      "Anti-inflammatory and antimicrobial",
      "Promotes healthy cholesterol levels",
    ],
    nutrition: {
      "Vitamin K": "Very high",
      "Vitamin A": "Good source",
      "Vitamin C": "Present",
      "Antioxidants": "Rich",
    },
    usage: [
      "Perfect garnish for curries and dals",
      "Add to tacos, salsas, and guacamole",
      "Finish soups and stews",
      "Mix into chutneys and dips",
      "Top rice dishes and biryanis",
    ],
    recipes: [
      {
        name: "Cilantro Micro Raita",
        description: "Mix cilantro microgreens into yogurt with roasted cumin, mint, and salt for a vibrant raita.",
      },
    ],
    storage: "Refrigerate and use within 5–7 days for best aroma.",
  },
  {
    slug: "pea-shoots",
    name: "Pea Shoots",
    tagline: "Sweet Garden Delicacy",
    emoji: "🫛",
    color: "#4d8b5c",
    bgGradient: "from-emerald-50 to-teal-100",
    flavor: "Fresh, sweet pea flavor — like biting into a garden",
    texture: "Tender with curling tendrils and delicate leaves",
    category: "Legume",
    growDays: "10-14 days",
    featured: false,
    image: "/images/pea-shoots.jpg",
    excerpt: "Pea shoots are beloved by chefs worldwide for their sweet flavor and elegant appearance. They're also packed with Vitamins A, C, and folate.",
    benefits: [
      "Rich in Vitamins A and C",
      "High in folate — essential for pregnancy",
      "Good plant-based protein source",
      "Supports immune function",
      "Anti-aging antioxidants",
    ],
    nutrition: {
      "Vitamin C": "7× more than blueberries",
      "Vitamin A": "Excellent source",
      "Folate": "Very high",
      "Protein": "Good source",
    },
    usage: [
      "Perfect raw in salads — no dressing needed",
      "Add to stir-fries at the very end",
      "Top pasta dishes and risottos",
      "Use in spring rolls and dumplings",
      "Garnish soups and clear broths",
    ],
    recipes: [
      {
        name: "Pea Shoot Stir Fry",
        description: "Quickly sauté pea shoots with garlic, sesame oil, soy sauce, and a squeeze of lemon for 60 seconds.",
      },
    ],
    storage: "Refrigerate and consume within 5–7 days.",
  },
  {
    slug: "radish",
    name: "Radish",
    tagline: "Spicy & Vibrant",
    emoji: "🌶",
    color: "#c0392b",
    bgGradient: "from-red-50 to-rose-100",
    flavor: "Spicy, peppery radish bite",
    texture: "Crisp with bold magenta or white stems",
    category: "Brassica",
    growDays: "6-10 days",
    featured: false,
    image: "/images/radish.jpg",
    excerpt: "Radish microgreens bring a satisfying peppery kick and stunning visual contrast to any dish, while delivering powerful detox benefits.",
    benefits: [
      "Supports liver and kidney detoxification",
      "Rich in Vitamin C and folate",
      "Digestive health support",
      "Anti-inflammatory properties",
      "Natural antibacterial compounds",
    ],
    nutrition: {
      "Vitamin C": "High",
      "Folate": "Good",
      "Anthocyanins": "Very high (purple varieties)",
      "Glucosinolates": "Rich",
    },
    usage: [
      "Add spice to sushi and sashimi",
      "Mix into tacos for heat and color",
      "Top avocado toast for a kick",
      "Add to grain bowls for visual contrast",
      "Mix into salad dressings",
    ],
    recipes: [
      {
        name: "Spicy Micro Avocado Toast",
        description: "Layer smashed avocado on sourdough, top with radish microgreens, everything bagel seasoning, and a drizzle of chili oil.",
      },
    ],
    storage: "Refrigerate and use within 5–7 days.",
  },
  {
    slug: "kohlrabi",
    name: "Kohlrabi",
    tagline: "Mild & Versatile",
    emoji: "🥬",
    color: "#6b9e5e",
    bgGradient: "from-green-50 to-emerald-100",
    flavor: "Mild, slightly sweet broccoli-like flavor",
    texture: "Tender and crisp",
    category: "Brassica",
    growDays: "8-12 days",
    featured: false,
    image: "/images/kohlrabi.jpg",
    excerpt: "Kohlrabi microgreens are mild and highly versatile — perfect for those who prefer a gentler flavor while still getting maximum nutrition.",
    benefits: [
      "Rich in Vitamin C and Vitamin B6",
      "Supports immune and metabolic health",
      "High in dietary fiber",
      "Potassium for heart health",
      "Antioxidant protection",
    ],
    nutrition: {
      "Vitamin C": "High",
      "Vitamin B6": "Good source",
      "Fiber": "High",
      "Potassium": "Present",
    },
    usage: [
      "Add to salads and coleslaws",
      "Use in wraps and sandwiches",
      "Top soups and stews",
      "Mix into grain bowls",
      "Pair with hummus as a dipper",
    ],
    recipes: [
      {
        name: "Kohlrabi Slaw",
        description: "Toss kohlrabi microgreens with shredded apple, lemon, olive oil, salt, and toasted walnuts.",
      },
    ],
    storage: "Keep refrigerated and use within 5–7 days.",
  },
  {
    slug: "mustard",
    name: "Mustard",
    tagline: "Bold & Spicy",
    emoji: "🌿",
    color: "#c8a415",
    bgGradient: "from-yellow-50 to-lime-100",
    flavor: "Intensely spicy, sharp, and peppery",
    texture: "Delicate leaves with slender stems",
    category: "Brassica",
    growDays: "7-10 days",
    featured: false,
    image: "/images/mustard.jpg",
    excerpt: "Mustard microgreens pack a serious spicy punch — they're the go-to choice for anyone who loves bold, assertive flavors in their greens.",
    benefits: [
      "Natural antibacterial and antifungal properties",
      "Rich in Vitamins A, C, and K",
      "Supports respiratory health",
      "High in omega-3 fatty acids",
      "Powerful glucosinolates",
    ],
    nutrition: {
      "Vitamin A": "High",
      "Vitamin C": "Good",
      "Vitamin K": "Excellent",
      "Omega-3": "Present",
    },
    usage: [
      "Add kick to burgers and sandwiches",
      "Mix into spicy salad dressings",
      "Garnish Indian street food",
      "Add to curries as a fresh garnish",
      "Mix into raita or chutneys",
    ],
    recipes: [
      {
        name: "Spicy Mustard Micro Chutney",
        description: "Blend mustard microgreens with mint, green chili, lemon juice, and salt for a zesty chutney.",
      },
    ],
    storage: "Refrigerate and consume within 5–7 days.",
  },
  {
    slug: "pok-choi",
    name: "Pok Choi",
    tagline: "Asian Garden Classic",
    emoji: "🥬",
    color: "#3d7a5e",
    bgGradient: "from-teal-50 to-green-100",
    flavor: "Mild, slightly sweet with subtle cabbage notes",
    texture: "Thick, juicy stems with broad leaves",
    category: "Brassica",
    growDays: "8-12 days",
    featured: false,
    image: "/images/pok-choi.jpg",
    excerpt: "Pok Choi microgreens bring the authentic flavor of Asian greens in miniature — perfect for stir-fries, Asian soups, and sushi rolls.",
    benefits: [
      "Rich in Vitamins A, C, and K",
      "Excellent source of calcium",
      "Supports bone density",
      "Anti-inflammatory compounds",
      "Supports thyroid health",
    ],
    nutrition: {
      "Vitamin K": "Very high",
      "Calcium": "Excellent source",
      "Vitamin A": "Rich",
      "Vitamin C": "Good",
    },
    usage: [
      "Perfect in Asian-style soups and broths",
      "Add to sushi rolls",
      "Use in stir-fries at the last minute",
      "Top ramen and noodle bowls",
      "Mix into spring rolls",
    ],
    recipes: [
      {
        name: "Pok Choi Miso Soup",
        description: "Add fresh pok choi microgreens to miso soup with tofu and wakame just before serving.",
      },
    ],
    storage: "Refrigerate and use within 5–7 days.",
  },
];

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug) || null;
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}

export function getRelatedProducts(currentSlug, count = 3) {
  return products.filter((p) => p.slug !== currentSlug).slice(0, count);
}
